#ifndef PINOUT_H
#define PINOUT_H

// ===== SERVOMOTEURS SG90 =====
#define SERVO_JAMBE_GAUCHE_PIN  18
#define SERVO_JAMBE_DROITE_PIN 19
#define SERVO_PIED_GAUCHE_PIN 21
#define SERVO_PIED_DROIT_PIN 22

// ===== CAPTEUR ULTRASON HC-SR08 =====
#define ULTRASONIC_ECHO_PIN 14
#define ULTRASONIC_TRIG_PIN 15


#endif
